name: Deploy snapshots

# see https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  release:
    name: Release on Sonatype OSS
    runs-on: ubuntu-latest
    if: github.repository_owner == 'hazelcast'

    steps:
      - uses: actions/checkout@v5
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: 'maven'
      - name: Publish to Apache Maven Central
        run: |
          PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          if [[ "$PROJECT_VERSION" == *-SNAPSHOT ]]; then
            mvn --activate-profiles release deploy
          fi
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_OSS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_OSS_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_ARGS: --batch-mode --no-transfer-progress
